Repository aplatkouski/rslang, pull requests merged in 2021-04, with the labels that each got.

#19 feat: add requirements.md
  Requirements.md
Labels: documentation

#15 actions to WordCard
  src/app/sectionPage/SectionPage.tsx
  src/constants.ts
  src/features/hardOrDeletedWordsPage/HardOrDeletedWordsPage.tsx
  src/features/studiedWordsPage/StudiedWordsPage.tsx
  src/features/wordCard/FormattedText.tsx
  src/features/wordCard/WordCard.tsx
  src/features/wordCard/styles.ts
  src/features/words/wordsSlice.ts
  src/types.ts
Labels: enhancement

#31 refactor: minor changes in userSlice.ts
  src/app/navbar/Navbar.tsx
  src/features/logInForm/LogInForm.tsx
  src/features/user/userSlice.ts
  src/types.ts
Labels: refactor

#44 fix side-menu
  src/app/sidemenu/SideMenu.tsx
  src/features/savannah-game/SavannahGame.tsx
Labels: bug
